### PR TITLE
Update scatterplot tool for rpy2

### LINKED ISSUE #385: Make scatterplot tool conda-ready

### PR DESCRIPTION
**Pull request by mvdbeek**
Depends on https://github.com/galaxyproject/cargo-port/pull/97 and https://github.com/galaxyproject/tools-iuc/pull/921 and closes #385

### CODE REVIEW

**Comment by jmchilton** [comment]
@mvdbeek I was going to work on updating the Travis recipe for the new planemo but if you are on it I'll let you take over :smile:.

 - It is pushed now so you don't need to tweak the pip line anymore.

```
  - export GALAXY_RELEASE=release_16.04
  - export CONDA_PREFIX="$HOME/conda"
```

Should be

```
  - export GALAXY_RELEASE=release_16.07
  - export PLANEMO_CONDA_PREFIX="$HOME/conda"
```

Planemo will just pick up an use that variable now.

This line can be dropped hopefully:

```
  - pip install --upgrade setuptools
```

**Comment by jmchilton** [comment]
```
Traceback (most recent call last):
  File "./scripts/functional_tests.py", line 120, in <module>
    driver_util.drive_test(find_test_driver())
  File "/tmp/tmphc3PLm/galaxy-dev/test/base/driver_util.py", line 694, in drive_test
    sys.exit(test_driver_class().run())
  File "/tmp/tmphc3PLm/galaxy-dev/test/base/driver_util.py", line 569, in run
    self.setup()
  File "/tmp/tmphc3PLm/galaxy-dev/test/base/driver_util.py", line 637, in setup
    self.app = build_galaxy_app(galaxy_config)
  File "/tmp/tmphc3PLm/galaxy-dev/test/base/driver_util.py", line 463, in build_galaxy_app
    app = GalaxyUniverseApplication( **simple_kwargs )
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/app.py", line 97, in __init__
    self._configure_toolbox()
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/config.py", line 823, in _configure_toolbox
    self.reload_toolbox()
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/config.py", line 809, in reload_toolbox
    self.toolbox = tools.ToolBox( tool_configs, self.config.tool_path, self )
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/tools/__init__.py", line 109, in __init__
    app=app,
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 1059, in __init__
    self._init_dependency_manager()
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/tools/toolbox/base.py", line 1072, in _init_dependency_manager
    self.dependency_manager = build_dependency_manager( self.app.config )
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/tools/deps/__init__.py", line 44, in build_dependency_manager
    dependency_manager = DependencyManager( **dependency_manager_kwds )
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/tools/deps/__init__.py", line 87, in __init__
    self.dependency_resolvers = self.__build_dependency_resolvers( conf_file )
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/tools/deps/__init__.py", line 129, in __build_dependency_resolvers
    plugin_source = plugin_config.plugin_source_from_path( conf_file )
  File "/tmp/tmphc3PLm/galaxy-dev/lib/galaxy/util/plugin_config.py", line 71, in plugin_source_from_path
    return ('xml', ElementTree.parse( path ).getroot())
  File "/opt/python/2.7.9/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/opt/python/2.7.9/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/opt/python/2.7.9/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/opt/python/2.7.9/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: duplicate attribute: line 2, column 70
```

Looks like a bug in planemo's building of dependency_resolves_conf.xml. I'll try to fix and do a new release.

**Comment by jmchilton** [comment]
Probably this https://github.com/galaxyproject/planemo/commit/f7b6c7ef89b2b54a4d7b14014d06a78e4bbfb2d9

**Comment by jmchilton** [comment]
Pushed a new release and rerunning the Travis build. I didn't test the fix per se so lets see what happens.

**Comment by jmchilton** [comment]
Awesome sauce the new .travis.yml worked well - :+1: on that part of this from me. I guess this should wait on galaxyproject/tools-iuc#921 for now though.

**Comment by mvdbeek** [comment]
This is also ready and tested from TTS (under my own account).

**Comment by bgruening** [comment]
Works for me! Thanks!

**Comment by mvdbeek** [comment]
@martenson can we get an upload?

**Comment by bgruening** [comment]
@martenson does it make sense for you to also implement such automatic upload mechanism like IUC has?

**Comment by martenson** [comment]
@mvdbeek done
@bgruening I think it does, but I did not even learn how you do it, yet mirror that feature. 😞

**Pull request merged**
