### PR TITLE
Add Data Manager for Bowtie2.

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by bgruening** [comment]
:+1: 

General data manager question: Can we include tests for small genomes?

**Comment by blankenberg** [comment]
We definitely should do this. Should be easy enough to do for planemo usage and I'll go ahead and look into that.

**Comment by jmchilton** [comment]
xref 
https://github.com/galaxyproject/planemo/issues/39
https://github.com/galaxyproject/planemo/issues/11

**Comment by martenson** [comment]
@blankenberg is this ready for merging or do you want to add the mentioned tests?

**Comment by martenson** [comment]
ping @blankenberg

**Comment by blankenberg** [comment]
Haven't had time to add tests yet unfortunately, and not sure when I'll get it it. So up to you guys about the merge.

**Comment by martenson** [comment]
fine with me without tests, will merge tomorrow unless objections arise

**Comment by bgruening** [comment]
:+1: thanks Dan!

**Pull request merged**
