### PR TITLE
Fix --output-tags argument in samtools mpileup

### PR DESCRIPTION
**Pull request by blankenberg**

### CODE REVIEW

**Comment by bgruening** [comment]
:+1:

**Comment by jennaj** [comment]
Hi all - do we have an ETA when this will make its way to http://usegalaxy.org? Testing today confirms it is still an issue and users are reporting bugs. It has been problem on Main since at least 8/12 (over two months).

ping @natefoo @davebx @blankenberg

**Comment by natefoo** [comment]
@jennaj Should be there already since it's in 15.10, and usegalaxy.org is on 15.10.

**Comment by martenson** [comment]
@natefoo I doubt that since it wasn't even on MTS until I uplaoded it there few minutes ago

**Comment by martenson** [comment]
I updated the usegalaxy.org, @jennaj please test.

**Comment by martenson** [comment]
https://usegalaxy.org/root?tool_id=toolshed.g2.bx.psu.edu/repos/devteam/samtools_mpileup/samtools_mpileup/2.1

**Comment by natefoo** [comment]
@martenson Spluh, didn't even realize what repo I'm in.

**Comment by jennaj** [comment]
Hi - am testing out 2.1 but noticed that:

1. re-run of 2.0 is not prompting users about the upgraded version. Older tools versions normally do this.
2. re-run is not populating the 2.1 form with the 2.0 prior settings when swapping versions. Most tools do this for options that are the same between versions.

Ok, test just finished and failed. 2.1 has a new error. Sent it in as a bug report for full details.

Fatal error: Exit code 139 (Error)
[main] unrecognized command '--version'

**Comment by martenson** [comment]
@jennaj ad 1. and 2 please create a new issue in galaxy repo, that is most probably Galaxy's problem

I created a new issue in this repo for the new 2.1 problems.

**Pull request merged**
