### PR TITLE
Update cufflinks_wrapper.py

### PR DESCRIPTION
**Pull request by bgruening**
Without this change we will get the following error:
```
Usage: cufflinks_wrapper.py [options]
cufflinks_wrapper.py: error: --compatible-hits-norm option requires an argument
```

### CODE REVIEW

**Comment by bgruening** [comment]
Do we need to increasing the version number? I think it was not able to use this option. So actually it should not affect reproducibility.

**Comment by nsoranzo** [comment]
:+1: 

No need to increase version number IMO.

**Comment by bgruening** [comment]
@nsoranzo thanks for reviewing!
@martenson can you please update this? It's an important bugfix.

**Comment by martenson** [comment]
Repository tools-devteam/tool_collections/cufflinks/cufflinks updated successfully.

**Comment by martenson** [comment]
updated on test.galaxyproject.org too

**Pull request merged**
