### PR TITLE
Update data_manager_bowtie2_index_builder to add to tophat2_indexes …

### PR DESCRIPTION
**Pull request by blankenberg**
…when checkbox is checked (default) in addition to bowtie2_indexes.

Did not actually test, but someone probably should.

### CODE REVIEW

**Comment by jennaj** [comment]
Dan, could I add this to a local and test (plus a cloud, got one!) once it is in the Tool Shed? Do I have to wait or is there another way to install it? 

Aaaannnd, thank you for taking care of this so quickly, appreciated! jen

**Comment by nitesh1989** [comment]
This is just the data manager fix, not the run data managers script in the cloudman playbook. I'll send in a PR for that. I thought that was what @blankenberg was talking about.

**Comment by bgruening** [comment]
@nitesh1989 have you tested it? Can we merge this one. It looks good to me.

**Comment by nitesh1989** [comment]
@bgruening I'm trying to test this, got the data_manager to run on my local instance, but can't seem to get tophat to see the bowtie2 indexes. Were you able to test this?

**Comment by bgruening** [comment]
Not yet, busy with a workshop. Have you reloaded the index or restarted Galaxy?

**Comment by nitesh1989** [comment]
It works. I've tested it.

**Comment by nitesh1989** [comment]
+1

**Pull request merged**
