### PR TITLE
Fixes for WeightedAverage tool.

### PR DESCRIPTION
**Pull request by blankenberg**
Addresses #399.

Purposely written to maintain python 2.4 compatibility.

### CODE REVIEW

**Comment by bgruening** [comment]
@blankenberg do you mind removing it from the tt_blacklist and get it under conda testing?

**Comment by martenson** [comment]
I removed it from the blacklist, tests running now.

**Comment by martenson** [comment]
`from galaxy.tools.util.galaxyops import *`

It seems this tool actually imports from Galaxy instead of its packages? Similar to https://github.com/galaxyproject/tools-devteam/issues/389

```
 Dataset Job Standard Output:
|  discarding /home/travis/conda/envs/iuc_conda/bin from PATH
|  prepending /tmp/tmpifhHhj/job_working_directory/000/6/conda-env/bin to PATH
| Dataset Job Standard Error:
|  Traceback (most recent call last):
|  File "/home/travis/build/galaxyproject/tools-devteam/tools/weightedaverage/WeightedAverage.py", line 11, in <module>
|  from galaxy.tools.util.galaxyops import *
|  File "/tmp/tmpifhHhj/galaxy-dev/lib/galaxy/tools/__init__.py", line 18, in <module>
|  from mako.template import Template
|  ImportError: No module named mako.template
```

**Comment by nsoranzo** [comment]
@martenson This PR seems to contain commits from another PR of mine, can you rebase?

**Comment by martenson** [comment]
@nsoranzo That shouldn't affect anything I believe, they are already merged, just github is not displaying it right.

**Comment by nsoranzo** [comment]
> It seems this tool actually imports from Galaxy instead of its packages? Similar to #389
> 
> from galaxy.tools.util.galaxyops import *
> ...

Indeed :cry: 
Since you are working on this, can you fix the `*` import with only the needed symbols?

**Comment by martenson** [comment]
@nsoranzo I have no idea what it uses from that asterisk import. I thinkI am just going to put it back into the blacklist...

**Comment by martenson** [comment]
Merged present in the blacklist, making this tool conda-compatible is a job for future us.

**Pull request merged**
