### PR TITLE
bwa - add dbKey to output bwa

### PR DESCRIPTION
**Pull request by kaktus42**
BWA tool now adds the dbKey of the reference sequence to the output bam.

PS: This repo is newer than what is on the toolshed, right? When do you update the toolshed?

### CODE REVIEW

**Comment by bgruening** [comment]
Nice! Could you add please a test for this function!

**Comment by nsoranzo** [comment]
I think only `dbKeyActions` needs to be a macro, the other 2 are used only once.

**Comment by kaktus42** [comment]
@bgruening And How would I do that?
@nsoranzo For me redundancy reduction is not the only reason to use macros. In this case e.g. for structuring

**Comment by nsoranzo** [comment]
@kaktus42 I'm ok with that.

**Comment by kaktus42** [comment]
ping @bgruening

**Comment by bgruening** [comment]
Thanks @kaktus42!

**Pull request merged**
