### PR TITLE
Backport packages from iuc to devteam.

### PR DESCRIPTION
**Pull request by mvdbeek**
addresses issue #298

### CODE REVIEW

**Comment by mvdbeek** [comment]
@bgruening you'll have to upload the packages as I don't have the toolshed credentials for devteam.

**Comment by bgruening** [comment]
Not sure if I have them :)
@hrhotz can you test this locally?

**Comment by bgruening** [comment]
@mvdbeek wait ... with back porting I meant to include the the changes to old recipes. Completely new recipes should not be added I think. @nsoranzo what do you think?

**Comment by mvdbeek** [comment]
They are not completely new though. They exist in the toolsheds.

**Comment by nsoranzo** [comment]
@mvdbeek You should update the files in `legacy/` subdirectory.

**Comment by mvdbeek** [comment]
@nsoranzo 
ahh, I hadn't noticed those.

**Comment by mvdbeek** [comment]
@nsoranzo @bgruening alright, let me know if the changes are okay. Perhaps I should exclude updates to the .shed.yml ?

**Comment by bgruening** [comment]
Do we need to change the repository_url?

**Comment by mvdbeek** [comment]
@bgruening do you mean from `https://github.com/galaxyproject/tools-devteam/tree/master/packages/package_cairo_1_12_14 `to `https://github.com/galaxyproject/tools-devteam/tree/master/legacy/package_cairo_1_12_14` ?
Or just to completely omit the remote_repository_url

**Comment by bgruening** [comment]
I mean to include the `legacy`

**Comment by mvdbeek** [comment]
@bgruening done.

**Comment by martenson** [comment]
I will deploy these as devteam. Thanks a lot guys.

**Comment by hrhotz** [comment]
Hi Bjoern (@bgruening <https://github.com/bgruening>)

sorry for joining late. Do you still want me to do something....though, I
am currently struggle to understand the whole issue.

Regards

**Comment by bgruening** [comment]
Hi @hrhotz,

assuming @martenson has updated the ToolShed, try to get the update and recompile the dependency. This PR fixes a OS-X specific issue and adds some more exports to your ENV.

I hope this will fix it for you!
Thanks see you soon,
Bjoern

**Comment by martenson** [comment]
@bgruening he indeed did

**Comment by bgruening** [comment]
Thanks @martenson!

**Pull request merged**
