### PR TITLE
Fix the BWA tools to require version 0.7.12 of the BWA package.

### PR DESCRIPTION
**Pull request by gregvonkuster**
The versions of these tools have been updated to be 0.4.2.

### CODE REVIEW

**Comment by bgruening** [comment]
:+1:

**Comment by mvdbeek** [comment]
:+1:

**Comment by mvdbeek** [comment]
@martenson can you upload this one too, please?

**Comment by martenson** [comment]
@mvdbeek I uploaded iuc/package_bwa_0_7_12 and then updated devteam/bwa
Thanks guys!

**Pull request merged**
