### PR TITLE
Add option for reporting unmapped.bam

### PR DESCRIPTION
**Pull request by puva**
Useful to extract unmapped reads for further analysis (i.e. identification of expressed viral sequences from human RNA-Seq data)

### CODE REVIEW

**Comment by nsoranzo** [comment]
:+1: 

Ciao Paolo!

**Comment by puva** [comment]
Ciao Nicola,
a presto con altre pull request!
P

**Comment by nsoranzo** [comment]
Tool version should be increased.

**Comment by puva** [comment]
Should be ok now!

**Comment by nsoranzo** [comment]
Any other comments? If not, I will merge this tomorrow.

**Comment by bgruening** [comment]
:+1: sorry for being so late to the party. Thanks a lot @puva!

**Pull request merged**
