### PR TITLE
Minor updates to kraken.

### PR DESCRIPTION
**Pull request by davebx**
Set the kraken DB path in an environment variable.
Remove the histogram output definition.
Fix for when no external FASTA files are defined.

### CODE REVIEW

**Comment by bgruening** [comment]
If the select is `optional="False"` this should not happen afaik and `optional="False"` is the default setting if not given, isn't?

**Comment by nsoranzo** [comment]
Moreover, even if `$input_fasta` is empty, `$fasta` cannot be `None`.

**Comment by davebx** [comment]
I just checked locally. When no input fasta is provided, `$input_fasta` contains: `['None']`

**Comment by nsoranzo** [comment]
This sounds like a Galaxy bug, I would expect `[]`.

**Comment by bgruening** [comment]
@davebx I would consider this a Galaxy bug.
Can you add an explicit "optional='True'" to this argument?

**Comment by nsoranzo** [comment]
@bgruening You mean `optional="false"`, don't you?

**Comment by davebx** [comment]
The input fasta option should actually be optional, kraken-build doesn't *require* providing additional sequences for building its libraries.

**Comment by bgruening** [comment]
@nsoranzo I guess it's either a `database` or a `FASTA file` or both, as far as I can see. 
@davebx knows this  it better.

**Comment by blankenberg** [comment]
In the very least, that 'None' should actually be a NoneDataset object that has a boolean value of False (via __nonzero__)  and a str() of "None" (as is the case for a single optional dataset).

But, the probable behavior of a multiple dataset that is optional with no option selected should be an empty iterable with boolean value of False (via __nonzero__ and __len__=0), that when the iterable is directly hit with str() should result in "None".

**Comment by nsoranzo** [comment]
@blankenberg I suggested a simple `[]`, but an empty iterable works as well :)

**Comment by blankenberg** [comment]
In a tool command tag/config file, etc:

Is str(multiple_dataset) output as ```'["path1", "path2"]'```, where str(single_dataset) is ```"path1"```?
Whereas str( multiple_select ) is output as ```'value1,value2'```, with str(single_select) as ```"value1"```? 

if so, yikes.

**Comment by bgruening** [comment]
@blankenberg seems to yes :(

**Comment by blankenberg** [comment]
Well thats not good, I'd consider ```str(multiple_dataset) output as '["path1", "path2"]'``` to be a bug, but I wonder if any tool has actually been designed to anticipate this behavior.

**Comment by davebx** [comment]
Rebased #148

**Comment by bgruening** [comment]
@blankenberg do we want to fill this as bug? Can we grep in the TS to see if this was already used?

**Comment by blankenberg** [comment]
@bgruening Yes, we should do both, although a bit more complicated to grep for a tool expecting a string representation of a list.

**Comment by bgruening** [comment]
@blankenberg can we merge this? The `bug` is on your ToDo list right? ;)

**Comment by blankenberg** [comment]
I am +1 with the merge.

Made a trello card: https://trello.com/c/WPxFNRqq for this issue, although I am happy if someone else wants to get to it before I have a chance.

**Pull request merged**
