### PR TITLE
Remove symlinked utils, add utils.

### PR DESCRIPTION
**Pull request by davebx**
This addresses #333, which also affects gops intersect.

### CODE REVIEW

**Comment by martenson** [comment]
if we are messing with this we probably should move the util folder to `tool_collections/gops/util`and symlink the files from all subtools thus fixing the current state and leveraging the power of symlinks

**Comment by davebx** [comment]
Wouldn't we still encounter planemo not resolving symlinked folders?

**Comment by martenson** [comment]
:+1:

**Comment by lparsons** [comment]
Thanks! Let me know when this gets pushed to the main ts and I'll update.

**Comment by martenson** [comment]
@lparsons done

**Comment by lparsons** [comment]
Great, everything seems to work now. Thanks!

**Comment by martenson** [comment]
glad to hear that!

**Comment by lparsons** [comment]
Just making a note: need to update biostar: https://biostar.usegalaxy.org/p/15974/#15977 and get back to Richard Poole on the Galaxy-Dev mailing list...

**Comment by martenson** [comment]
@lparsons I responded to that email, thanks for reminding

**Pull request merged**
