### PR TITLE
Migrate gffread to IUC

### PR DESCRIPTION
**Pull request by lparsons**
Migrate the gffread utility to the IUC via https://github.com/galaxyproject/tools-iuc/pull/2665

### CODE REVIEW

**Comment by bgruening** [comment]
Mh, I considered legacy really as lagacy-tools that are not maintained. I don't see a point in moving them. :(

**Comment by martenson** [comment]
`/legacy` is exactly for that purpose, those are tools that made it to the IUC already.

**Comment by bgruening** [comment]
@martenson merge or shift them to legacy? Your call.

**Comment by nsoranzo** [comment]
I think it was agreed to remove migrated tools from now on and clean up `legacy/` .

**Pull request merged**
