### PR TITLE
remove additional inputs from the user interface

### PR DESCRIPTION
**Pull request by bgruening**
This can be done with `multiple=True`.

### CODE REVIEW

**Comment by bgruening** [comment]
Thanks to Pavan for spotting this.

**Comment by jmchilton** [comment]
It is this way intentionally - for now you can only substitute a single collection into the ``multiple=True`` data input - but you may wish to supply multiple collections to this tool - right? That is why that repeat is there and the input type only allows collections.

I'll admit this is confusing - maybe we should update the help on the repeat input instead.

**Comment by bgruening** [comment]
John what happens if you add more than one collection? Would it be the same result as putting all files into one collection instead of two?

**Comment by martenson** [comment]
ping @jmchilton - please have a look

**Comment by jmchilton** [comment]
Yes @bgruening - if you look at the for loop - they are all just sort of merged together in one big list of files to pass into the tool.

**Comment by martenson** [comment]
Thank you for the clarification. Closing now.

**Pull request closed without merging**
