### PR TITLE
Picard rnaseqmetrics + GTF

### PR DESCRIPTION
**Pull request by yhoogstrate**
The picard tool for RNA-Seq metrics makes use of a format referred to as refFlat. This is not a very commonly used format which caries more or less the same information as GTF/GFF files. Therefore this patch that allows to also make use of those formats.

Due to all the changes with respect to conda, I don't know if the test will pass.

### CODE REVIEW

**Comment by bwlang** [comment]
I love this idea!

**Comment by bgruening** [comment]
@yhoogstrate please ping me. I keep loosing track. This is great!
Do you have time to get picard under conda testing entirely and remove the tool_dependencies.xml file?
If not please increase the tool version and I will merge it.

Thanks!

**Comment by bgruening** [comment]
@yhoogstrate can you please rebase?

**Comment by bgruening** [comment]
Great stuff!

**Pull request merged**
