### PR TITLE
Remove gffread optional

### PR DESCRIPTION
**Pull request by martenson**
change at L212 - the rest is whitespace

### CODE REVIEW

**Comment by nsoranzo** [comment]
:+1:

**Comment by guerler** [comment]
:+1:

**Comment by jmchilton** [comment]
Wait guys - we shouldn't need to change working tools for changes in Galaxy. This tag doesn't cause Galaxy to die in 14.10 or 15.01.

**Comment by martenson** [comment]
@jmchilton revert is here: https://github.com/galaxyproject/tools-devteam/pull/328

**Comment by guerler** [comment]
Thanks @martenson.

**Comment by martenson** [comment]
@guerler
let's talk about this in https://github.com/galaxyproject/galaxy/issues/980

**Comment by nsoranzo** [comment]
@martenson Can you push this to the MTS?

**Comment by martenson** [comment]
@nsoranzo done, sorry for the delay

**Comment by nsoranzo** [comment]
@martenson NP, thanks!

**Pull request merged**
