### PR TITLE
Allow for inverse selection (filtering out)

### PR DESCRIPTION
**Pull request by zfrenchee**
Partially solves #348

### CODE REVIEW

**Comment by zfrenchee** [comment]
How do people feel about this @bgruening ?

**Comment by bgruening** [comment]
I feel good about it, because the tests are passing :) So at least this will not break anything.
Sorry for not answering your mail so fast.
Anyone else? @davebx?

**Comment by davebx** [comment]
Looks solid to me.

**Comment by bgruening** [comment]
@davebx could you please update this wrapper?

**Comment by bgruening** [comment]
Thanks a lot @zfrenchee for working on this!

**Comment by bgruening** [comment]
@davebx I'm not sure but @zfrenchee probably needs this in usegalaxy.org. Is there a chance to update this as well?

**Comment by zfrenchee** [comment]
I'm actually running my own server!

**Comment by bgruening** [comment]
Even better :)

**Comment by davebx** [comment]
I've updated both sheds.

Thanks for the contribution, @zfrenchee

**Comment by zfrenchee** [comment]
I don't think this actually worked, sadly. I'm trying to understand the [samtools source](https://github.com/samtools/samtools/blob/develop/sam_view.c) and although I'm not sure I think it might be the case that a `-U` flag alone won't do it.

**Comment by zfrenchee** [comment]
See https://github.com/samtools/samtools/issues/551#issuecomment-204566822

**Pull request merged**
