### PR TITLE
Update cuff_macros.xml

### PR DESCRIPTION
**Pull request by bgruening**
fixes https://github.com/galaxyproject/tools-devteam/issues/228

@blankenberg what do you think about this fix?

### CODE REVIEW

**Comment by blankenberg** [comment]
another alternative: https://github.com/galaxyproject/tools-devteam/pull/231

**Comment by bgruening** [comment]
@blankenberg please decide what we want to do here. I don't think pipe is a good solution, but feel free to decide this.

**Comment by bgruening** [comment]
ping @blankenberg

**Comment by nsoranzo** [comment]
This has been solved by commit https://github.com/galaxyproject/tools-devteam/commit/8434d197771a311f78b50e3c5293e135df28f978 .

**Pull request closed without merging**
