### PR TITLE
Fix for sam_to_bam when sam does not include header information

### PR DESCRIPTION
**Pull request by scholtalbers**
The previous cmd tried to run samtools sort first, which would fail on a sam without header. This fixes that.

### CODE REVIEW

**Comment by bgruening** [comment]
@scholtalbers can you please increase the version number of the tool.

**Comment by bgruening** [comment]
@scholtalbers can you please check your last commit? You reverted you initial changes?

**Comment by scholtalbers** [comment]
yeah, I forgot that I reverted the changes to actually test that the added test fails with the original tool wrapper.

**Comment by bgruening** [comment]
This looks good now. Anyone else? @erasche @nsoranzo @peterjc ?

**Comment by bgruening** [comment]
Thanks @scholtalbers!

**Pull request merged**
