### PR TITLE
Add auto option to coverage_search conditional in TopHat

### PR DESCRIPTION
**Pull request by nsoranzo**
See #365 .

Ping @jennaj.

### CODE REVIEW

**Comment by jennaj** [comment]
+1 (but I don't really get to vote officially, this is just for liking the improved modeling of params  :) )

**Comment by martenson** [comment]
@jennaj of course you get to vote! 
https://github.com/galaxyproject/galaxy/blob/dev/doc/source/project/organization.rst#members

**Comment by bgruening** [comment]
Do we want to update to tophat 2.1.0 and bowtie 2.2.8? This would enable conda testing as well.

**Comment by nsoranzo** [comment]
I can update to tophat 2.1.0, but there's no package_bowtie_2_2_8 yet.

**Comment by nsoranzo** [comment]
@bgruening I've updated the wrapper to use TopHat 2.1.0 and removed the tool from the blacklist. There should be no need to use Bowtie 2.2.8 since 2.2.5 is already in Bioconda, but its build.sh seems broken (binaries are not moved to `bin/`). Compare:
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bowtie2/2.2.5/build.sh
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/bowtie2/build.sh

Can you fix that?

**Comment by nsoranzo** [comment]
I've fixed Bowtie2 2.2.5 in Bioconda, now tests pass. Merge?

**Comment by bgruening** [comment]
Indeed thanks Nicola!

**Pull request merged**
