### PR TITLE
Freebayes update

### PR DESCRIPTION
**Pull request by nekrut**
Modifications to freebayes:

- fixed bug related to 'naive_w_filters' option (this was broken in the original version -> command line was never generated for this option)
- updated dependencies to 0.9.20-tagged release of freebayes

### CODE REVIEW

**Comment by martenson** [comment]
:+1:

**Comment by blankenberg** [comment]
:+1:

**Comment by nekrut** [comment]
so merge god damn it :stuck_out_tongue_winking_eye:

**Comment by bgruening** [comment]
Merging is possible even from a train ;)

**Comment by nekrut** [comment]
we don't have trains here - hence merging in impossible!

**Comment by martenson** [comment]
updated on main TS

**Comment by martenson** [comment]
Latest version installed on https://test.galaxyproject.org/

**Pull request merged**
