### PR TITLE
Implement changes used by IUC

### PR DESCRIPTION
**Pull request by erasche**
Makes travis quieter/easier to read, test the tools, and fail only on errors (not citation warnings

### CODE REVIEW

**Comment by erasche** [comment]
Looks like failing here:

```
+Linting tool /home/travis/build/galaxyproject/tools-devteam/tool_collections/fastx_toolkit/fastq_to_fasta/fastq_to_fasta.xml
Applying linter xml_ordering... WARNING
.. WARNING: Best practice violation [outputs] elements should come before [tests]
Applying linter top_level... FAIL
.. ERROR: Tool does not define a version attribute.
Applying linter citations... WARNING
.. WARNING: No citations found, consider adding citations to your tool.
Failed linting
```

Added as `1.0.0`, as that's the default, if memory serves...

**Comment by jmchilton** [comment]
The 1.0.0 seems like the right thing to do here - thanks.

**Comment by peterjc** [comment]
Yes - looks like we need to do another sweep for missing version numbers (maybe some more tools were migrated into this repository, or I just missed some).

@jmchilton does planemo lint spot missing a version string?

**Comment by erasche** [comment]
@peterjc yep, that's how I caught this one.

**Comment by peterjc** [comment]
Lovely :+1:

**Pull request merged**
