### PR TITLE
Remove sort_by for build/indexes

### PR DESCRIPTION
**Pull request by scholtalbers**
If you guys think this is a good idea this removes sort_by from all tools (except for legacy/bwa).
Relates: #251

### CODE REVIEW

**Comment by bgruening** [comment]
@scholtalbers any reason to remove this?
I'm +/- 0 on this. It is kind of a documentation and tell others how to sort for other columns.

**Comment by scholtalbers** [comment]
@bgruening I have some legacy build keys (different nomenclature) that I cannot or want to remove due to stored workflows and histories. I prepended their labels/names with (legacy) and put them at the bottom of the .loc files. For some tools this works, for others that have sort_by this doesn't and they appear at the top. I could prepend them differently, or maybe there is a filter I can place?(i did not look into this option yet) 
But I guess the main point is that the behavior can be different between tools and as an admin I would like to control which builds are shown first - those that are mainly used.

**Comment by bgruening** [comment]
ping @blankenberg

**Comment by blankenberg** [comment]
Now that we can type to search within these select elements, the alphabetical sorting is not nearly as important as before -- where the ordering in the flat files usually just reflected the 'random' ordering that they were created and added.

However, while scrolling it is nice to e.g. see all of the 'Human' builds together.

I'm like +.00001 on this, since an admin could manually reorder the original files to get the same outcome as the sort option (although this would be a manual step needed to get back to 'old look') and the searching feature in the select lists easing finding selections in large lists.

**Comment by scholtalbers** [comment]
@blankenberg, could there be a default sorting when fetching data from .loc
files - which would also be reflected on the admin "local data" pages? This
would at least make it uniform (unless.. someone has a different sort_by in
the tool xml of course).

**Comment by bgruening** [comment]
@scholtalbers any string feeling about this one or can we close it?

**Comment by scholtalbers** [comment]
I don't mind if you close it. Although I do still feel that the sorting of the references/builds should not be the responsibility of the tool :).

**Comment by bgruening** [comment]
@scholtalbers thats probably true. But than a github issue on the Galaxy main repo is the right place :)
Thanks!

**Pull request closed without merging**
