### PR TITLE
tophat_fusion_post: additional parameters

### PR DESCRIPTION
**Pull request by jsh58**
Additional parameters added to wrapper.  Use of CDATA, best practices.

### CODE REVIEW

**Comment by bgruening** [comment]
I like this!
Could you also run `planemo lint` on it.
ping  @blankenberg 

Thanks  @jsh58!

**Comment by jsh58** [comment]
Updated tool wrapper -- reordered sections, added citation, added test.  Now passes planemo lint.  

However, the test does NOT work.  The wrapper uses the $__get_data_table_entry__() function and the 'dbkey' value of the input BAM file.  With the test dataset (test-data/accepted_hits.bam), the value of $accepted_hits.dbkey is not set, and I don't know how to set it.  With it unset, the blast_db_path and Bowtie indexes are not established, and the tool fails to run.

**Comment by blankenberg** [comment]
```<param name="accepted_hits" value="accepted_hits.bam" dbkey="some_value" ftype="bam"/>```

**Comment by jsh58** [comment]
That still fails the test, for me.

**Comment by bgruening** [comment]
@blankenberg does the tests ever worked? Testing indices was not possible a long time. Merge anyway?

**Pull request closed without merging**
