### PR TITLE
migrate out kraken, samtools, vcflib; move to legacy

### PR DESCRIPTION
**Pull request by martenson**
counterpart of https://github.com/galaxyproject/tools-iuc/pull/1148

**do not merge before the above #1148 is merged**

### CODE REVIEW

**Comment by martenson** [comment]
when merging, squash it please

**Comment by bgruening** [comment]
Thanks @martenson!

**Comment by martenson** [comment]
yay, thanks all!

**Comment by martenson** [comment]
@bgruening you did not squash it, did you?

**Pull request merged**
