### PR TITLE
Move old gatk tools to legacy/

### PR DESCRIPTION
**Pull request by nsoranzo**
Also:
- Move tools in legacy to a `tools/` subdir
- Update and sort `.tt_skip` file

Close https://github.com/galaxyproject/tools-devteam/issues/546 .

### CODE REVIEW

**Comment by bernt-matthias** [comment]
One could also rename `legacy` to `deprecated ` (in analogy to IUC)?

**Comment by nsoranzo** [comment]
> One could also rename `legacy` to `deprecated ` (in analogy to IUC)?

I don't mind either way, but all other changes here are still needed.

**Comment by nsoranzo** [comment]
> Then I would prefer `deprecated` in order to keep it as close to IUC as possible.

OK, done in a rebase.

**Comment by bernt-matthias** [comment]
Do you think anyone else cares about this? Otherwise I would merge.

**Comment by nsoranzo** [comment]
> Do you think anyone else cares about this? Otherwise I would merge.

I think you can safely go ahead if you are happy with it (we can always revert).

**Pull request merged**
