### PR TITLE
fix small issue with data manager

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Is it just quoting and indentation or am I missing something else? The GitHub diff doesn't help.

**Comment by bgruening** [comment]
This is currently one spacing and a wrongly places `"`. But this DM is not working for me. It produced invalid fasta files. I try to understand this.

**Comment by bgruening** [comment]
I see this as fasta header if I try to get sequences from UCSC `chr2L.fa0000664000462000024300013142324610636536751011716 0ustar  angieprotein>chr2L`
@blankenberg have you seen this before?

**Comment by gregvonkuster** [comment]
Hmm...not that it may be of any help here, but I've used this tool a lot (including on a fresh install today) and haven't seen this behavior.

**Comment by bgruening** [comment]
@gregvonkuster can you pleas verify that it is this DM with the dbkey in the name, there are two. If so are you using UCSC? This is reproducible in my Docker container for rna-seq 17.01 :(

It looks like every fasta entry gets the uncompressed version added as well into the first line.

**Comment by bgruening** [comment]
@gregvonkuster which organism are you trying?

**Comment by bgruening** [comment]
For example `dm6.fa.gz` does not have a chromFA file - is this working for you?

**Comment by gregvonkuster** [comment]
Oh, sorry, I guess I must be using a different DM - I'm using ```data_manager_fetch_genome_dbkeys_all_fasta```, not ```data_manager_fetch_genome_all_fasta_dbkey```.   :(  The tool ids are so close, hmm...

Today I installed human - hg19 and hg38, but I've not installed dm6.

**Comment by bgruening** [comment]
I think that is the DM we are talking about the naming is just confusing - thats the only one with dbkey in its name in the TS.
I get for all genomes that can be installed something like:
```
root@992afed16249:/galaxy-central# grep -a '>' tool-data/dm3/seq/dm3.fa 
chr2L.fa0000664000462000024300013142324610636536751011716 0ustar  angieprotein>chr2L
chr2LHet.fa0000664000462000024300000133670410636536753012357 0ustar  angieprotein>chr2LHet
chr2R.fa0000664000462000024300012222016210636536754011717 0ustar  angieprotein>chr2R
chr2RHet.fa0000664000462000024300001462766310636536755012402 0ustar  angieprotein>chr2RHet
chr3L.fa0000664000462000024300013737730410636536756011735 0ustar  angieprotein>chr3L
chr3LHet.fa0000664000462000024300001174302310636536760012353 0ustar  angieprotein>chr3LHet
chr3R.fa0000664000462000024300015445007210636536761011730 0ustar  angieprotein>chr3R
chr3RHet.fa0000664000462000024300001162727410636536763012375 0ustar  angieprotein>chr3RHet
chr4.fa0000664000462000024300000520512510636536763011601 0ustar  angieprotein>chr4
chrM.fa0000664000462000024300000004671210636536772011632 0ustar  angieprotein>chrM
chrU.fa0000664000462000024300004706345010636536764011654 0ustar  angieprotein>chrU
chrUextra.fa0000664000462000024300016066657110636536766012733 0ustar  angieprotein>chrUextra
chrX.fa0000664000462000024300012717637210636536770011663 0ustar  angieprotein>chrX
chrXHet.fa0000664000462000024300000062651410636536772012312 0ustar  angieprotein>chrXHet
chrYHet.fa0000664000462000024300000126330410636536772012306 0ustar  angieprotein>chrYHet
root@992afed16249:/galaxy-central# grep -a '>' tool-data/dm2/seq/dm2.fa 
chr2L.fa0000664000462000024300013142324610636536751011716 0ustar  angieprotein>chr2L
chr2LHet.fa0000664000462000024300000133670410636536753012357 0ustar  angieprotein>chr2LHet
chr2R.fa0000664000462000024300012222016210636536754011717 0ustar  angieprotein>chr2R
chr2RHet.fa0000664000462000024300001462766310636536755012402 0ustar  angieprotein>chr2RHet
chr3L.fa0000664000462000024300013737730410636536756011735 0ustar  angieprotein>chr3L
chr3LHet.fa0000664000462000024300001174302310636536760012353 0ustar  angieprotein>chr3LHet
chr3R.fa0000664000462000024300015445007210636536761011730 0ustar  angieprotein>chr3R
chr3RHet.fa0000664000462000024300001162727410636536763012375 0ustar  angieprotein>chr3RHet
chr4.fa0000664000462000024300000520512510636536763011601 0ustar  angieprotein>chr4
chrM.fa0000664000462000024300000004671210636536772011632 0ustar  angieprotein>chrM
chrU.fa0000664000462000024300004706345010636536764011654 0ustar  angieprotein>chrU
chrUextra.fa0000664000462000024300016066657110636536766012733 0ustar  angieprotein>chrUextra
chrX.fa0000664000462000024300012717637210636536770011663 0ustar  angieprotein>chrX
chrXHet.fa0000664000462000024300000062651410636536772012312 0ustar  angieprotein>chrXHet
chrYHet.fa0000664000462000024300000126330410636536772012306 0ustar  angieprotein>chrYHet
```

under python2 and python3 how can this be?

**Comment by bgruening** [comment]
@gregvonkuster can you try this please in a Docker container.

**Comment by mvdbeek** [comment]
hmm, the dm isn't working at all for me right now:
```
Traceback (most recent call last):
  File "/Users/mvandenb/src/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/86fa71e9b427/data_manager_fetch_genome_dbkeys_all_fasta/data_manager/data_manager_fetch_genome_all_fasta_dbkeys.py", line 454, in <module>
    main()
  File "/Users/mvandenb/src/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/86fa71e9b427/data_manager_fetch_genome_dbkeys_all_fasta/data_manager/data_manager_fetch_genome_all_fasta_dbkeys.py", line 447, in main
    REFERENCE_SOURCE_TO_DOWNLOAD[ params['param_dict']['reference_source']['reference_source_selector'] ]( data_manager_dict, params, target_directory, dbkey, dbkey_name, sequence_id, sequence_name, tmp_dir )
  File "/Users/mvandenb/src/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/86fa71e9b427/data_manager_fetch_genome_dbkeys_all_fasta/data_manager/data_manager_fetch_genome_all_fasta_dbkeys.py", line 278, in download_from_ucsc
    add_fasta_to_table(data_manager_dict, fasta_readers, target_directory, dbkey, dbkey_name, sequence_id, sequence_name, params)
  File "/Users/mvandenb/src/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/86fa71e9b427/data_manager_fetch_genome_dbkeys_all_fasta/data_manager/data_manager_fetch_genome_all_fasta_dbkeys.py", line 270, in add_fasta_to_table
    for data_table_name, data_table_entry in _stream_fasta_to_file( fasta_readers, target_directory, dbkey, dbkey_name, sequence_id, sequence_name, params ):
  File "/Users/mvandenb/src/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/86fa71e9b427/data_manager_fetch_genome_dbkeys_all_fasta/data_manager/data_manager_fetch_genome_all_fasta_dbkeys.py", line 366, in _stream_fasta_to_file
    compute_fasta_length( fasta_filename, os.path.join( target_directory, len_base_name ), keep_first_word=True )
  File "/Users/mvandenb/src/shed_tools/toolshed.g2.bx.psu.edu/repos/devteam/data_manager_fetch_genome_dbkeys_all_fasta/86fa71e9b427/data_manager_fetch_genome_dbkeys_all_fasta/data_manager/data_manager_fetch_genome_all_fasta_dbkeys.py", line 400, in compute_fasta_length
    fasta_title = fasta_title.split()[0]
IndexError: list index out of range
```
The old one without the dbkey still works though.
Which is very strange, because there was a time when the old one wasn't working since they removed the non-compressed versions, IIRC.

**Comment by bgruening** [comment]
This error I haven't seen :)
Which genome was this?

**Comment by mvdbeek** [comment]
dm3

**Comment by mvdbeek** [comment]
OK, I think I got it, there's a problem properly unpacking tar.gz.

**Comment by nsoranzo** [comment]
@bgruening I've included your fixes in https://github.com/galaxyproject/tools-iuc/pull/1151/commits/9614122e1a6afa084d81a5ab45fbe5c1985e086f .

@mvdbeek If you manage to fix the bugs, it is probably worth to target the above PR instead of tools-devteam.

**Comment by mvdbeek** [comment]
Sure, will do.

**Comment by blankenberg** [comment]
> I see this as fasta header if I try to get sequences from UCSC chr2L.fa0000664000462000024300013142324610636536751011716 0ustar angieprotein>chr2L
> @blankenberg have you seen this before?

Looks like you have probably figured this out, but this is a tar header. Usually a result from decompressing, but not untaring.

**Pull request closed without merging**
