### PR TITLE
add R as dependency

### PR DESCRIPTION
**Pull request by bgruening**
CollectInsertSizeMetrics need Rscript for plotting.

### CODE REVIEW

**Comment by nsoranzo** [comment]
According to https://broadinstitute.github.io/picard/command-line-overview.html#MeanQualityByCycle also MeanQualityByCycle needs R.

**Comment by nsoranzo** [comment]
By grepping for `RExecutor` in Picard source code, it seems R is needed by: CollectBaseDistributionByCycle, CollectGcBiasMetrics, CollectInsertSizeMetrics, CollectRnaSeqMetrics, CollectRrbsMetrics (no wrapper for this), MeanQualityByCycle and QualityScoreDistribution.

**Comment by bgruening** [comment]
Will update this PR accordingly ...

**Comment by bgruening** [comment]
ping @nsoranzo @nekrut

**Comment by nsoranzo** [comment]
:+1:

Thanks Björn!

**Comment by bgruening** [comment]
Thanks for reviewing!

**Pull request merged**
