### PR TITLE
Update and test Bowtie

### PR DESCRIPTION
**Pull request by nsoranzo**
- Update to bowtie 1.1.2 to enable Conda testing.
- Add a small test genome with indexes (8 MB, cannot be smaller), with test data table and loc file. Indexes comes from https://bitbucket.org/natefoo/galaxy-test-data
- Test the assigned dbkey when using an indexed reference genome

### CODE REVIEW

**Comment by bgruening** [comment]
Looks good, I'm just worried about the test-data size. We need to have a mechanism in planemo to download test-data from depot if it's not available locally.

**Comment by nsoranzo** [comment]
@bgruening I've updated the PR to really test the tool (removing it from `.tt_blacklist`) and excluding the test genome indexes from TS upload.

**Comment by bgruening** [comment]
Thanks, I'm also worried about the github size. But if no one else objects I will merge this evening.

Thanks again!

**Comment by mvdbeek** [comment]
Thanks @nsoranzo !

**Comment by bgruening** [comment]
Ha, thanks! :)

**Comment by mvdbeek** [comment]
@martenson can we get this into the toolsheds please?

**Comment by mvdbeek** [comment]
@martenson nevermind, I got confused with the bowtie_color_wrappers. sorry.

**Pull request merged**
