### PR TITLE
remove "unsorted" option from picard SortSam

### PR DESCRIPTION
**Pull request by bgruening**
for @jennaj and https://github.com/galaxyproject/tools-devteam/issues/160

### CODE REVIEW

**Comment by jennaj** [comment]
Optionally include help comments on the tool form that explain what this option does (modifies the SO: header). Either OK with me now that it has been clarified.

**Comment by nsoranzo** [comment]
So we close this?

**Comment by bgruening** [comment]
I'm fine with removing this option.

**Comment by nsoranzo** [comment]
@nekrut opinions?

**Comment by bgruening** [comment]
Can we merge this one as well?

**Comment by bgruening** [comment]
@nekrut any ideas here?

**Comment by bgruening** [comment]
ping @jennaj @nekrut

**Comment by jennaj** [comment]
@bgruening my vote was always "yes" to remove it since it seems way simpler, but I was ok with the other (documenting what it did). but @nekrut and the devs have the final say. \

Sorry for late reply - I missed this somehow!

**Comment by bgruening** [comment]
@jennaj @nekrut @nsoranzo I rebased the changes and I'm ready to merge this.

**Comment by nsoranzo** [comment]
:+1:

**Comment by jennaj** [comment]
As an informal way of tracking final testing, could we please leave this open and track when the updated tool moves through these steps: 

1) in the main tool shed
2) installed successfully and tested on:
  a) http://usegalaxy.org
  b) Local (default getgalaxy.org, master branch) 
  c) Cloudman (default cloudlaunch, running latest master)

After all completed, give the final "go" and close out the ticket.

Sound OK?

**Comment by martenson** [comment]
@jennaj this is a Pull Request. Unless we actually close it nothing will change. Only after the close the changes will get merged into the codebase. We cannot 'leave it open'.

**Comment by bgruening** [comment]
@jennaj: @martenson is right, this is not possible here. But it is possible in your original issue #160 
You have a fair point that we are missing to distribute these fixes/enhancement. @erasche is working on an automatic TTS upload. But installing on cloudman and Test is something only the devteam can do.

Have a look at #160. I have added a template how you can structure your issue with a checkbox to keep track of this process.

**Comment by jennaj** [comment]
@bgruening excellent, I like the idea of tracking the resolution and final testing in the original ticket (which often describes the **observed** issue in detail w/ example data). The checkboxes are a simple way to track movement through these wrap-up steps. I may rearrange the contents a bit, all that was off the top of my head :) And suggestions from all are welcome.

Ideally, any user-side tool or important UI modifications would get some sort of default "Integration, Test, and Close" checklist. Install for main/test would be devteam of course, install local/cloud probably me along with UI testing on all three (but we can decide best path/who - could be different people depending on who knows what to look for in the testing).

We do all this anyway informally. Tracking to make sure all is done so users know when a tool is ready for use again was the primary goal.

**Pull request merged**
