### PR TITLE
Replace isinstance with is_of_type

### PR DESCRIPTION
**Pull request by nsoranzo**
xref. https://github.com/galaxyproject/galaxy/issues/3353

Also update a bit the affected tools to recent standard.

### CODE REVIEW

**Comment by mvdbeek** [comment]
Looks good, but tests didn't run. I'll open and close to see if it's being picked up.

**Comment by bgruening** [comment]
Since when is this in place? Should we increase the version number?

**Comment by mvdbeek** [comment]
2014-08-12 -- since it doesn't change the output I would say no.

**Comment by bgruening** [comment]
I was more worried about backwards compatibility but 2014 seems to be old enough to me! :)

**Comment by bgruening** [comment]
Thanks  @nsoranzo and @mvdbeek !

**Pull request merged**
