### PR TITLE
added '-f' flag to soft link (ln) commands. 

### PR DESCRIPTION
**Pull request by Takadonet**
Reason being is that if the job was requeued with slurm scheduler because a cluster node has died, the job_working_directory may not be empty and ln command fails because the soft link already exist.

### CODE REVIEW

**Comment by martenson** [comment]
this feels like something that should not be treated on the tool level but I do not know where else to put it :/

**Comment by Takadonet** [comment]
I agree but it's the easiest solution to our problem. We have very large workflow runs (1k jobs+) that cannot be  recovered because a few jobs died. Frustrating for our users to re-submit.

Planning to do a few more pull request to add that '-f' flag. If you are planning to accept this one.

**Comment by bgruening** [comment]
@martenson why does a new job get the same working directory? Is this a bug in the cleanup step?

**Comment by Takadonet** [comment]
Its not a clean up bug.  When a node dies on our slurm cluster,  the jobs
on it will keep report they are running.  Slurm has ability to requeue the
job to another node with same job id.  Since its the same job id,  galaxy
never find out that it was resubmited.

**Comment by bgruening** [comment]
@Takadonet there were a few SLURM bugs fixed recently. Is this still a problem for you? If so I will merge this. Sorry for taking such a long time.

**Comment by nsoranzo** [comment]
:+1: Looks safe.

**Comment by ericenns** [comment]
So I think the better solution to this problem is to auto clean the working directory in the job script sent to the cluster. This is still a problem for us, it isn't a slurm problem. The reason this happens is in our cluster jobs can get re queued if a higher priority job comes in. Then tools fail because they already ran for a bit and have partial output.

**Comment by bgruening** [comment]
@ericenns I tend to agree! Maybe this issue should be moved to the galaxy repo. In the meantime I'm open to fix it here. @Takadonet ?

**Comment by Takadonet** [comment]
I agree.  Please move to main repo

**Comment by bgruening** [comment]
Hi,

we worked a little bit on freebayes in the meantime. I just added it here: https://github.com/galaxyproject/tools-devteam/commit/ec3aa49a9d65ed3b69836c357e8a0278cd034a75

Thanks!

**Pull request closed without merging**
