### PR TITLE
remove lastz

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by nsoranzo** [comment]
I think we usually move them to `legacy/`

**Comment by bernt-matthias** [comment]
Hi @bgruening  what was the reason for this PR? I just stumbled over lastz because it fails for the CI that just ran for the tool: https://github.com/galaxyproject/tools-devteam/pull/558

Should we just (re)move it or fix it first?

**Comment by nsoranzo** [comment]
It's already in tools-iuc.

**Comment by bernt-matthias** [comment]
I see. Should we just move it to legacy (we should also add `legacy` to the exclude list in CI or rename the folder to deprecated for consistency with IUC repo structure)?

**Comment by nsoranzo** [comment]
@bernt-matthias We are not putting in legacy only stuff that is not worth to migrate to tools-iuc, see https://github.com/galaxyproject/tools-devteam/pull/532 .

**Comment by bernt-matthias** [comment]
Thanks for the clarification.

**Pull request merged**
