### PR TITLE
Cufflinks conda

### PR DESCRIPTION
**Pull request by lecorguille**
The PR aims to prepare cufflinks tool_collection to be conda ready.

###Cufflinks
I had deps for lib/galaxy/datatypes/util/gff_util.py which is called by [cufflinks_wrapper.py ](https://github.com/lecorguille/tools-devteam/blob/e9cb7de8b3789ecf6710faff54c88bb771b28a2d/tool_collections/cufflinks/cufflinks/cufflinks_wrapper.py#L9)
(it was tricky to solve because it seems a Galaxy library (so usually run in the .venv) but it's actually launched within the conda environment)

###Cuffdiff
I had to change the package name to fit with conda nomenclature.
I can change easily the ToolShed tooldependency package_cummerbund_2_8_2 from IUC to fit also with the conda nomenclature!?
https://github.com/galaxyproject/tools-iuc/blob/master/packages/package_cummerbund_2_8_2/tool_dependencies.xml#L9

```xml
 <package name="cummeRbund" version="2.8.2">
```
To
```xml
 <package name="bioconductor-cummerbund" version="2.8.2">
```

That way, we will remained compatible with both resolvers.

### CODE REVIEW

**Comment by lecorguille** [comment]
`planemo lint` is almost green
Except for:
 - cufflinks
```
/tmp/tmpQ6mkit:144:0:ERROR:SCHEMASV:SCHEMAV_CVC_DATATYPE_VALID_1_2_1: Element 'param', attribute 'type': 'hidden_data' is not a valid value of the atomic type 'ParamType'.
/tmp/tmpQ6mkit:190:0:ERROR:SCHEMASV:SCHEMAV_CVC_COMPLEX_TYPE_3_2_1: Element 'action', attribute 'type': The attribute 'type' is not allowed.]
```
 - cuffnorm 
```
.. WARNING: No valid test(s) found.
```

**Comment by lecorguille** [comment]
https://github.com/bioconda/bioconda-recipes/pull/2833

**Comment by bgruening** [comment]
@galaxyproject/iuc is this ready to go, before we migrate it?

**Comment by lecorguille** [comment]
@bgruening Related to this issue: https://github.com/galaxyproject/galaxy/pull/3133

**Comment by nsoranzo** [comment]
@bgruening It seems it can be removed, according to the issue referenced by @lecorguille.

**Comment by nsoranzo** [comment]
@lecorguille @bgruening Thanks for the work on this, I've also added some commits to this PR, it's finally all linted and green!

Ready for merge!

**Comment by lecorguille** [comment]
Thanks to you to having finalize this PR
I should have done myself.
Cheers!

**Comment by bgruening** [comment]
Cool!!!!

**Pull request merged**
