### PR TITLE
Add .shed.yml file for cummeRbund

### PR DESCRIPTION
**Pull request by bgruening**
fix https://github.com/galaxyproject/tools-devteam/issues/106

### CODE REVIEW

**Comment by nsoranzo** [comment]
So we go with the new TS repository?

**Comment by jj-umn** [comment]
I think so.  That would give the tool the devteam branding.

**Comment by bgruening** [comment]
Anyone? @nsoranzo?

**Comment by nsoranzo** [comment]
:+1: 

That was my only concern.

**Pull request merged**
