### PR TITLE
deprecate broken samtools pileup

### PR DESCRIPTION
**Pull request by bernt-matthias**
samtools mpileup is now at IUC

seems to be the last tool in the devteam repo that fails the weekly tests.

### CODE REVIEW

**Comment by bgruening** [comment]
ping @wm75

**Comment by nsoranzo** [comment]
pileup is different from mpileup (both as a tool and as a format), but the former has been deprecated since samtools 0.1.17 (6 July, 2011), so I think it's still fine to deprecate it.

Can you please move the `sam_pileup` directory in the `tools/` subdirectory of `deprecated/` ?

**Comment by bernt-matthias** [comment]
> Can you please move the `sam_pileup` directory in the `tools/` subdirectory of `deprecated/` ?

Yep. Also moved sam_merge -- which I misplaced as well :(

**Comment by nsoranzo** [comment]
> > Can you please move the `sam_pileup` directory in the `tools/` subdirectory of `deprecated/` ?
> 
> Yep. Also moved sam_merge -- which I misplaced as well :(

I already did that on master yesterday, can be removed from here.

**Comment by bernt-matthias** [comment]
fixed

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
