### PR TITLE
Add sanitizer

### PR DESCRIPTION
**Pull request by bgruening**

### CODE REVIEW

**Comment by bgruening** [comment]
Anyone?

**Comment by blankenberg** [comment]
Should we bump the version, since we're letting more chars through?

**Comment by bgruening** [comment]
More chars will not change the result of old tool runs, isn't it? Moreover, it will result in a new revision of all EMBOSS tools, because they are all in one repo, correct? I would vote for not increase but can do so :)

**Comment by bgruening** [comment]
Anyone?

**Comment by martenson** [comment]
lgtm, thanks @bgruening !

**Comment by bgruening** [comment]
Thanks for the merge!

**Comment by martenson** [comment]
uploaded to MTS

**Pull request merged**
