### PR TITLE
Conda-fy bamtools collection

### PR DESCRIPTION
**Pull request by gregvonkuster**

### CODE REVIEW

**Comment by bgruening** [comment]
Greg, this is great but can you please remove the lines from tt_blacklist please: https://github.com/galaxyproject/tools-devteam/blob/master/.tt_blacklist#L171

Only this will trigger tests!
Thanks!

**Comment by gregvonkuster** [comment]
Done, sorry I missed the blacklist entries @bgruening

**Comment by bgruening** [comment]
Please also for the other PR :)

**Comment by bgruening** [comment]
It's still not tested :(
Can you rebase this branch?

**Comment by gregvonkuster** [comment]
I'll open another PR.

**Pull request closed without merging**
