### PR TITLE
Fix cummeRbund and cummerbund_to_tabular

### PR DESCRIPTION
**Pull request by davebx**

### CODE REVIEW

**Comment by bgruening** [comment]
Do we need to depend now on sqlite? I think we have a repository in TTS.

**Comment by davebx** [comment]
If I'm not mistaken, it's built-in since 2.5.

**Comment by jmchilton** [comment]
https://docs.python.org/2/library/sqlite3.html

:+1:  Yes - this is excellent! We should not be importing galaxy stuff - it means we can never refactor Galaxy and also means we cannot reuse the tool shed artifacts outside of Galaxy. I like this a lot better.

**Comment by bgruening** [comment]
Very nice!  :+1:

**Pull request merged**
