### PR TITLE
Fix kraken2tax requirements and add test

### PR DESCRIPTION
**Pull request by mvdbeek**

### CODE REVIEW

**Comment by nsoranzo** [comment]
Should this tool be migrated to tools-iuc?

**Comment by mvdbeek** [comment]
What's the advantage ? I think these low-priority, not-frequrently-updated tools can live here

**Comment by mvdbeek** [comment]
I see now what the advantage is, but I think it's a nice motivation for https://github.com/galaxyproject/planemo-ci-action/pull/43 and community tool repos in general.

**Comment by nsoranzo** [comment]
Also we don't test this repo before a new Galaxy release, which won't be "fixed" by reusable workflows.

**Comment by mvdbeek** [comment]
> Also we don't test this repo before a new Galaxy release, which won't be "fixed" by reusable workflows.

We do, it's in the release process. I've just not done it recently.

**Comment by mvdbeek** [comment]
Actually, neither IUC nor devteam repo tests are part of the "official" release process. We don't do that for e.g bjoern's tools either, i don't think that should be a criterium one way or the other.

**Review by nsoranzo — APPROVED** [review]

**Pull request merged**
