### PR TITLE
Update Cut tool to match distribution.

### PR DESCRIPTION
**Pull request by blankenberg**
see also: https://github.com/galaxyproject/galaxy/pull/913

### CODE REVIEW

**Comment by bgruening** [comment]
:+1: 
Why do we have this wrapper in two places?

**Comment by bgruening** [comment]
ping @blankenberg

**Comment by blankenberg** [comment]
@bgruening The text utils were originally migrated to the toolshed and removed from the distribution, but then added back to the distribution. We should keep both copies in sync, or remove one. I have another set of changes that adds header options and step-size to ranges, that I'd like to push out as well.

**Comment by nsoranzo** [comment]
@blankenberg We can move the present version here to the `legacy/` subdirectory.

**Comment by bgruening** [comment]
I will merge this. @blankenberg please tell us if we should deprecate this tool here.

**Pull request merged**
