### PR TITLE
Implement --al / --al-conc option for bowtie2

### PR DESCRIPTION
**Pull request by mvdbeek**
bowtie2 supports outputting aligned reads into separate files, this PR implements this functionality. This considerably speeds up a pipeline we are working on that repeatedly extracts aligned reads ( as compared to bowtie2 -> bam -> reads ).

### CODE REVIEW

**Comment by bgruening** [comment]
Can you please increase the version number?
Wondering why is the traivs testing not working .. :(

**Comment by mvdbeek** [comment]
@bgruening it seems with the version bump travis started the test.

**Comment by bgruening** [comment]
Tests are fine. I guess it would be nice to add new tests for the new output files. But for now ... let's merge it.

**Comment by mvdbeek** [comment]
Can someone form the devteam upload this to the toolshed? ping @martenson @davebx

**Comment by martenson** [comment]
@mvdbeek done, thanks fellas

**Comment by mvdbeek** [comment]
Thanks @martenson @bgruening!

**Pull request merged**
